/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { CompletionService } from "../completion.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { CompletionCreateInput } from "./CompletionCreateInput";
import { Completion } from "./Completion";
import { CompletionFindManyArgs } from "./CompletionFindManyArgs";
import { CompletionWhereUniqueInput } from "./CompletionWhereUniqueInput";
import { CompletionUpdateInput } from "./CompletionUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class CompletionControllerBase {
  constructor(
    protected readonly service: CompletionService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Completion })
  @nestAccessControl.UseRoles({
    resource: "Completion",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createCompletion(
    @common.Body() data: CompletionCreateInput
  ): Promise<Completion> {
    return await this.service.createCompletion({
      data: {
        ...data,

        codeSnippet: data.codeSnippet
          ? {
              connect: data.codeSnippet,
            }
          : undefined,
      },
      select: {
        codeSnippet: {
          select: {
            id: true,
          },
        },

        confidenceScore: true,
        createdAt: true,
        id: true,
        text: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Completion] })
  @ApiNestedQuery(CompletionFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Completion",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async completions(@common.Req() request: Request): Promise<Completion[]> {
    const args = plainToClass(CompletionFindManyArgs, request.query);
    return this.service.completions({
      ...args,
      select: {
        codeSnippet: {
          select: {
            id: true,
          },
        },

        confidenceScore: true,
        createdAt: true,
        id: true,
        text: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Completion })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Completion",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async completion(
    @common.Param() params: CompletionWhereUniqueInput
  ): Promise<Completion | null> {
    const result = await this.service.completion({
      where: params,
      select: {
        codeSnippet: {
          select: {
            id: true,
          },
        },

        confidenceScore: true,
        createdAt: true,
        id: true,
        text: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Completion })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Completion",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateCompletion(
    @common.Param() params: CompletionWhereUniqueInput,
    @common.Body() data: CompletionUpdateInput
  ): Promise<Completion | null> {
    try {
      return await this.service.updateCompletion({
        where: params,
        data: {
          ...data,

          codeSnippet: data.codeSnippet
            ? {
                connect: data.codeSnippet,
              }
            : undefined,
        },
        select: {
          codeSnippet: {
            select: {
              id: true,
            },
          },

          confidenceScore: true,
          createdAt: true,
          id: true,
          text: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Completion })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Completion",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteCompletion(
    @common.Param() params: CompletionWhereUniqueInput
  ): Promise<Completion | null> {
    try {
      return await this.service.deleteCompletion({
        where: params,
        select: {
          codeSnippet: {
            select: {
              id: true,
            },
          },

          confidenceScore: true,
          createdAt: true,
          id: true,
          text: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
