/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  CodeSnippet as PrismaCodeSnippet,
  Completion as PrismaCompletion,
  Suggestion as PrismaSuggestion,
  User as PrismaUser,
} from "@prisma/client";

export class CodeSnippetServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.CodeSnippetCountArgs, "select">
  ): Promise<number> {
    return this.prisma.codeSnippet.count(args);
  }

  async codeSnippets(
    args: Prisma.CodeSnippetFindManyArgs
  ): Promise<PrismaCodeSnippet[]> {
    return this.prisma.codeSnippet.findMany(args);
  }
  async codeSnippet(
    args: Prisma.CodeSnippetFindUniqueArgs
  ): Promise<PrismaCodeSnippet | null> {
    return this.prisma.codeSnippet.findUnique(args);
  }
  async createCodeSnippet(
    args: Prisma.CodeSnippetCreateArgs
  ): Promise<PrismaCodeSnippet> {
    return this.prisma.codeSnippet.create(args);
  }
  async updateCodeSnippet(
    args: Prisma.CodeSnippetUpdateArgs
  ): Promise<PrismaCodeSnippet> {
    return this.prisma.codeSnippet.update(args);
  }
  async deleteCodeSnippet(
    args: Prisma.CodeSnippetDeleteArgs
  ): Promise<PrismaCodeSnippet> {
    return this.prisma.codeSnippet.delete(args);
  }

  async findCompletions(
    parentId: string,
    args: Prisma.CompletionFindManyArgs
  ): Promise<PrismaCompletion[]> {
    return this.prisma.codeSnippet
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .completions(args);
  }

  async findSuggestions(
    parentId: string,
    args: Prisma.SuggestionFindManyArgs
  ): Promise<PrismaSuggestion[]> {
    return this.prisma.codeSnippet
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .suggestions(args);
  }

  async getUser(parentId: string): Promise<PrismaUser | null> {
    return this.prisma.codeSnippet
      .findUnique({
        where: { id: parentId },
      })
      .user();
  }
}
