/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { SuggestionService } from "../suggestion.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { SuggestionCreateInput } from "./SuggestionCreateInput";
import { Suggestion } from "./Suggestion";
import { SuggestionFindManyArgs } from "./SuggestionFindManyArgs";
import { SuggestionWhereUniqueInput } from "./SuggestionWhereUniqueInput";
import { SuggestionUpdateInput } from "./SuggestionUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class SuggestionControllerBase {
  constructor(
    protected readonly service: SuggestionService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Suggestion })
  @nestAccessControl.UseRoles({
    resource: "Suggestion",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createSuggestion(
    @common.Body() data: SuggestionCreateInput
  ): Promise<Suggestion> {
    return await this.service.createSuggestion({
      data: {
        ...data,

        codeSnippet: data.codeSnippet
          ? {
              connect: data.codeSnippet,
            }
          : undefined,
      },
      select: {
        codeSnippet: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        relevance: true,
        text: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Suggestion] })
  @ApiNestedQuery(SuggestionFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Suggestion",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async suggestions(@common.Req() request: Request): Promise<Suggestion[]> {
    const args = plainToClass(SuggestionFindManyArgs, request.query);
    return this.service.suggestions({
      ...args,
      select: {
        codeSnippet: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        relevance: true,
        text: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Suggestion })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Suggestion",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async suggestion(
    @common.Param() params: SuggestionWhereUniqueInput
  ): Promise<Suggestion | null> {
    const result = await this.service.suggestion({
      where: params,
      select: {
        codeSnippet: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        relevance: true,
        text: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Suggestion })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Suggestion",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateSuggestion(
    @common.Param() params: SuggestionWhereUniqueInput,
    @common.Body() data: SuggestionUpdateInput
  ): Promise<Suggestion | null> {
    try {
      return await this.service.updateSuggestion({
        where: params,
        data: {
          ...data,

          codeSnippet: data.codeSnippet
            ? {
                connect: data.codeSnippet,
              }
            : undefined,
        },
        select: {
          codeSnippet: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          relevance: true,
          text: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Suggestion })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Suggestion",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteSuggestion(
    @common.Param() params: SuggestionWhereUniqueInput
  ): Promise<Suggestion | null> {
    try {
      return await this.service.deleteSuggestion({
        where: params,
        select: {
          codeSnippet: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          relevance: true,
          text: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
